import { generateAudio } from './app/agent/researchAgent.js';

async function testOpenAI() {
    console.log("Testing OpenAI TTS...");
    const text = "OpenAI Audio Test: This narration is generated by the Alloy voice.";
    const id = "openai_test";
    
    try {
        const file = await generateAudio(text, id);
        console.log("Result File:", file);
        if (file && file.endsWith('.mp3')) {
            console.log("SUCCESS: Generated MP3 file.");
        } else {
            console.error("FAILURE: unexpected output or null.");
        }
    } catch (e) {
        console.error("Test Error:", e);
    }
}

testOpenAI();
